[build]
  # Perintah ini menjalankan instalasi Node.js dan Python
  command = "npm install && pip install -r requirements.txt && npm run build"

  # Asumsi folder output (hasil build) adalah 'dist'
  publish = "dist" 

[build.environment]
  # Semua variabel lingkungan di sini
  NODE_VERSION = "18" # Memastikan versi Node.js
  PYTHON_VERSION = "3.11" # Memastikan versi Python
