[build]
  # Perintah untuk instalasi Node.js, Python, dan Build
  command = "npm install && pip install -r requirements.txt && npm run build"

  # Folder output hasil build
  publish = "dist" 

[build.environment]
  # Variabel lingkungan untuk Runtime
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.11"

