[build]
  # Perintah ini akan menjalankan instalasi Node.js dan Python secara berurutan
  command = "npm install && pip install -r requirements.txt && npm run build"

  # Asumsi folder output (hasil build) adalah 'dist'
  publish = "dist" 

[build.environment]
  PYTHON_VERSION = "3.11"
